#!/usr/bin/env bash

initial=false
if [ ! -f "vendor/autoload.php" ] || [ ! -f "node_modules/.package-lock.json" ]; then
    initial=true
fi

composer install --no-progress --no-interaction \
&& npm install --silent

if [ ! initial ]; then
    php artisan key:generate
fi

php artisan migrate \
&& php artisan clear-compiled \
&& php artisan config:clear \
&& php artisan route:clear \
&& php artisan optimize

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf