name: Run Tests

on:
  push:
    branches: ['*']

jobs:
  tests:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]
        php: [8.1]

    name: PHP${{ matrix.php }} - ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup database
      uses: shogo82148/actions-setup-mysql@v1
      with:
        distribution: 'mysql'
        mysql-version: '8.0'
        user: dbuser
        root-password: password
        password: dbpassword

    - name: Create test database
      run: mysql --user=dbuser --password=dbpassword --host=127.0.0.1 --execute='CREATE DATABASE IF NOT EXISTS ayp_test;SHOW DATABASES;'
      
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: cli, dom, curl, libxml, imap, mysql, mbstring, common, xml, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, gmp, redis, swoole, memcached, pcov, xdebug
        coverage: none

    - name: Install NPM/Composer Dependencies and compile assets
      run: |
        composer install
        npm install
        npm run build

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Execute tests (Unit and Feature tests) via Pest for ${{ matrix.module }} Module
      run: |
        php -r "file_exists('.env') || copy('.env.github', '.env');"
        php artisan key:generate
        php artisan migrate
        php artisan db:seed
        php artisan config:cache
        php artisan route:cache
        php artisan about
        php artisan test